
INSERT INTO STATUS (STATUS_ID, NAME) VALUES(1, 'UNCONFIRMED');
INSERT INTO STATUS (STATUS_ID, NAME) VALUES(2, 'CONFIRMED');

INSERT INTO RATINGS (RATING_ID, NAME) VALUES (1, 'G');
INSERT INTO RATINGS (RATING_ID, NAME) VALUES (2, 'PG');
INSERT INTO RATINGS (RATING_ID, NAME) VALUES (3, 'PG13');
INSERT INTO RATINGS (RATING_ID, NAME) VALUES (4, 'R');
INSERT INTO RATINGS (RATING_ID, NAME) VALUES (5, 'NC17');

INSERT INTO GENRES (GENRE_ID, NAME) VALUES (1, 'COMEDY');
INSERT INTO GENRES (GENRE_ID, NAME) VALUES (2, 'DRAMA');
INSERT INTO GENRES (GENRE_ID, NAME) VALUES (3, 'CARTOON');
INSERT INTO GENRES (GENRE_ID, NAME) VALUES (4, 'THRILLER');
INSERT INTO GENRES (GENRE_ID, NAME) VALUES (5, 'DOCUMENTARY');
INSERT INTO GENRES (GENRE_ID, NAME) VALUES (6, 'ACTION');
