name: CI/CD

# запуск CI/CD при пуш в ветку feature и пул-реквесте в ветки main и dev
on:
  push:
    branches:
      - feature
  pull_request:
    branches:
      - main
      - dev

# Работа, которая будет выполняться: сборка (build) и тестирование проекта. Будут запущены на виртуальной машине linux (ubuntu)
jobs:
  build-and-checkstyle-and-testing:
    runs-on: ubuntu-latest

    # Шаги, в которых описывается, что для проверки будут:
    # 1. скачан репозиторий (действие actions/checkout@v3)
    # 2. установлена java (действие actions/setup-java@v3) 11-ой версии
    # 3. проведена проверка стилистики кода (действие mvn checkstyle:check)
    # 4. осуществлена сборка проекта вместе с шагом тестирования (действие mvn clean install)
    # 5. пауза в 3 секунды
    # 6. прогнаны postman тесты (действие matt-ball/newman-action@master)
    steps:
      - name: Клонирование кода репозитория
        uses: actions/checkout@v3
      - name: Установка java 11-ой версии с maven
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Проверка стилистики (checkstyle)
      #  run: mvn checkstyle:check
      #- name: Сборка проекта и тестирование
        run: mvn clean install

      - name: Пауза 3с
        run: sleep 3s
        shell: bash
      - name: Start application
        run: mvn spring-boot:run -Dserver.port=8080 &

      - name: Run Postman tests
        run: npx newman run your_postman_collection.json --env-var baseUrl=http://localhost:8080

      - name: Stop application
        run: mvn spring-boot:stop
      
      #- name: Postman тестирование
      #  uses: matt-ball/newman-action@master
      #  with:
      #    collection: ./postman/filmorate.json
      #    envVar: '[{ "key": "baseUrl", "value": "http://localhost:8080" }]'
