name: CI/CD

# запуск CI/CD при пуш в ветку feature и пул-реквесте в ветки main и dev 
on:
  push:
    branches:
      - feature
  pull_request:
    branches:
      - main
      - dev

# Работа, которая будет выполняться: сборка (build) и тестирование проекта. Будут запущены на виртуальной машине linux (ubuntu)
jobs:
  build-and-checkstyle-and-testing:
    runs-on: ubuntu-latest

    # Шаги, которые будут выполнены
    steps:
      - name: Клонирование кода репозитория
        uses: actions/checkout@v3
      - name: Установка java 11-ой версии с maven
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
          
      - name: Проверка стилистики (checkstyle)
        run: mvn checkstyle:check -Dcheckstyle.config.location=checkstyle.xml
        
      - name: Сборка проекта и тестирование
        run: mvn clean install
        
      - name: Запуск приложения на порту 8080
        run: mvn spring-boot:run -Dserver.port=8080 &

      - name: Проход Postman тестов с baseUrl http://localhost:8080
        run: npx newman run ./postman/filmorate.json --env-var baseUrl=http://localhost:8080

      - name: Остановка приложения
        run: mvn spring-boot:stop
